/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AddressTypeEnum : addressType  * `ADDR` - Complete Postal Address * `BIZZ` - Business Address * `DLVY` - Delivery Address * `HOME` - Home Address * `MLTO` - Mail Address * `PBOX` - Post Office Box 
type AddressTypeEnum string

// List of AddressTypeEnum
const (
	ADDR AddressTypeEnum = "ADDR"
	BIZZ AddressTypeEnum = "BIZZ"
	DLVY AddressTypeEnum = "DLVY"
	HOME AddressTypeEnum = "HOME"
	MLTO AddressTypeEnum = "MLTO"
	PBOX AddressTypeEnum = "PBOX"
)