/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PersonalIdentificationCodeEnum : IdentificationCode:  * `1` - Passport Number * `2` - Tax Identification Number * `3` - Driver’s License Number * `4` - Alien Registration Number * `5` - Corporate Identification * `9` - Other Identification 
type PersonalIdentificationCodeEnum string

// List of PersonalIdentificationCodeEnum
const (
	_1 PersonalIdentificationCodeEnum = "1"
	_2 PersonalIdentificationCodeEnum = "2"
	_3 PersonalIdentificationCodeEnum = "3"
	_4 PersonalIdentificationCodeEnum = "4"
	_5 PersonalIdentificationCodeEnum = "5"
	_9 PersonalIdentificationCodeEnum = "9"
)