/*
 * WIRE API
 *
 * Moov WIRE implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// WireError struct for WireError
type WireError struct {
	// An error message describing the problem intended for humans.
	Error string `json:"error"`
}
