/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AdviceCodeEnum : AdviceCode  * `HLD - Hold * `LTR` - Letter * `PHN` - Phone * `TLX` - Telex * `WRE` - Wire  * 
type AdviceCodeEnum string

// List of AdviceCodeEnum
const (
	HLD AdviceCodeEnum = "HLD"
	LTR AdviceCodeEnum = "LTR"
	PHN AdviceCodeEnum = "PHN"
	TLX AdviceCodeEnum = "TLX"
	WRE AdviceCodeEnum = "WRE"
)