/*
 * Wire API
 *
 * Moov Wire implements an HTTP API for creating, parsing, and validating Fedwire messages.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ValidateOptions struct for ValidateOptions
type ValidateOptions struct {
	// Skip validation of the InputMessageAccountabilityData (IMAD) field
	SkipMandatoryIMAD bool `json:"skipMandatoryIMAD,omitempty"`
	// Allow FedWireMessage.SenderSupplied to be nil
	AllowMissingSenderSupplied bool `json:"allowMissingSenderSupplied,omitempty"`
}
