/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LocalInstrumentEnum : LocalInstrument  * `ANSI` - ANSI X12 format * `COVS` - Sequence B Cover Payment Structured * `GXML` - General XML format * `IXML` - ISO 20022 XML formaT * `NARR` - Narrative Text * `PROP` - Proprietary Local Instrument Code * `RMTS` - Remittance Information Structured * `RRMT` - Related Remittance Information * `S820` - STP 820 format * `SWIF` - SWIFT field 70 (Remittance Information) * `UEDI` - UN/EDIFACT format 
type LocalInstrumentEnum string

// List of LocalInstrumentEnum
const (
	ANSI LocalInstrumentEnum = "ANSI"
	COVS LocalInstrumentEnum = "COVS"
	GXML LocalInstrumentEnum = "GXML"
	IXML LocalInstrumentEnum = "IXML"
	NARR LocalInstrumentEnum = "NARR"
	PROP LocalInstrumentEnum = "PROP"
	RMTS LocalInstrumentEnum = "RMTS"
	RRMT LocalInstrumentEnum = "RRMT"
	S820 LocalInstrumentEnum = "S820"
	SWIF LocalInstrumentEnum = "SWIF"
	UEDI LocalInstrumentEnum = "UEDI"
)