/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MessageStatusIndicator : Message Status Indicator  Outgoing Messages * `0` - In process or Intercepted * `2` - Successful with Accounting (Value) * `3` - Rejected due to Error Condition * `7` - Successful without Accounting (Non-Value)  Incoming Messages * `N` - Successful with Accounting (Value) * `S` - Successful without Accounting (Non-Value) 
type MessageStatusIndicator string

// List of MessageStatusIndicator
const (
	_0 MessageStatusIndicator = "0"
	_2 MessageStatusIndicator = "2"
	_3 MessageStatusIndicator = "3"
	_7 MessageStatusIndicator = "7"
	N MessageStatusIndicator = "N"
	S MessageStatusIndicator = "S"
)