/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TypeCode : Type Code: * `10` - Funds Transfer * `15` - Foreign Transfer * `16` - Settlement Transfer 
type TypeCode string

// List of TypeCode
const (
	_10 TypeCode = "10"
	_15 TypeCode = "15"
	_16 TypeCode = "16"
)