/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// IdentificationCodeEnum : IdentificationCode: * `B` - SWIFT Bank Identifier Code (BIC) * `C` - CHIPS Participant * `D` - Demand Deposit Account (DDA) Number * `F` - Fed Routing Number * `T` - SWIFT BIC or Bank Entity Identifier (BEI) and Account Number * `U` - CHIPS Identifier * `1` - Passport Number * `2` - Tax Identification Number * `3` - Driver’s License Number * `4` - Alien Registration Number * `5` - Corporate Identification * `9` - Other Identification 
type IdentificationCodeEnum string

// List of IdentificationCodeEnum
const (
	B IdentificationCodeEnum = "B"
	C IdentificationCodeEnum = "C"
	D IdentificationCodeEnum = "D"
	F IdentificationCodeEnum = "F"
	T IdentificationCodeEnum = "T"
	U IdentificationCodeEnum = "U"
	_1 IdentificationCodeEnum = "1"
	_2 IdentificationCodeEnum = "2"
	_3 IdentificationCodeEnum = "3"
	_4 IdentificationCodeEnum = "4"
	_5 IdentificationCodeEnum = "5"
	_9 IdentificationCodeEnum = "9"
)