/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// IntermediaryFinancialInstitution
type IntermediaryFinancialInstitution struct {
	// ID Code B: SWIFT Bank Identifier Code (BIC) C: CHIPS Participant D: Demand Deposit Account (DDA) Number F: Fed Routing Number U: CHIPS Identifier
	IdCode string `json:"idCode,omitempty"`
}
