/*
 * Wire API
 *
 * Moov Wire implements an HTTP API for creating, parsing, and validating Fedwire messages.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InputMessageAccountabilityData struct for InputMessageAccountabilityData
type InputMessageAccountabilityData struct {
	// InputCycleDate (Format CCYYMMDD - C=Century, Y=Year, M=Month, D=Day)
	InputCycleDate string `json:"inputCycleDate"`
	// InputSource
	InputSource string `json:"inputSource"`
	// InputSequenceNumber
	InputSequenceNumber string `json:"inputSequenceNumber"`
}
