/*
 * Wire API
 *
 * Moov Wire implements an HTTP API for creating, parsing, and validating Fedwire messages.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PreviousMessageIdentifier The identifier for a previous message.
type PreviousMessageIdentifier struct {
	// PreviousMessageIdentifier
	PreviousMessageIdentifier string `json:"previousMessageIdentifier,omitempty"`
}
