/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RemittanceLocationMethodEnum : RemittanceLocationMethod  * `EDIC` - Electronic Data Interchange * `EMAL` - Email * `FAXI` - Fax * `POST` - Postal services * `SMS` - Short Message Service (text) * `URI` - Uniform Resource Identifier 
type RemittanceLocationMethodEnum string

// List of RemittanceLocationMethodEnum
const (
	EDIC RemittanceLocationMethodEnum = "EDIC"
	EMAL RemittanceLocationMethodEnum = "EMAL"
	FAXI RemittanceLocationMethodEnum = "FAXI"
	POST RemittanceLocationMethodEnum = "POST"
	SMS RemittanceLocationMethodEnum = "SMS"
	URI RemittanceLocationMethodEnum = "URI"
)