/*
 * Wire API
 *
 * Moov Wire implements an HTTP API for creating, parsing, and validating Fedwire messages.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Beneficiary struct for Beneficiary
type Beneficiary struct {
	Personal Personal `json:"personal"`
}
