/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SenderReference SenderReference is sender reference
type SenderReference struct {
	// SenderReference
	SenderReference string `json:"senderReference,omitempty"`
}
