/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BusinessFunctionCodeEnum : BusinessFunctionCode * `BTR` - Bank Transfer (Beneficiary is a bank) * `DRC` - Customer or Corporate Drawdown Request * `CKS` - Check Same Day Settlement * `DRW` - Drawdown Payment * `CTP` - Customer Transfer Plus * `FFR` - Fed Funds Returned * `CTR` - Customer Transfer (Beneficiary is a not a bank) * `FFS` - Fed Funds Sold * `DEP` - Deposit to Sender’s Account * `SVC` - Service Message * `DRB` - Bank-to-Bank Drawdown Request 
type BusinessFunctionCodeEnum string

// List of BusinessFunctionCodeEnum
const (
	BTR BusinessFunctionCodeEnum = "BTR"
	DRC BusinessFunctionCodeEnum = "DRC"
	CKS BusinessFunctionCodeEnum = "CKS"
	DRW BusinessFunctionCodeEnum = "DRW"
	CTP BusinessFunctionCodeEnum = "CTP"
	FFR BusinessFunctionCodeEnum = "FFR"
	CTR BusinessFunctionCodeEnum = "CTR"
	FFS BusinessFunctionCodeEnum = "FFS"
	DEP BusinessFunctionCodeEnum = "DEP"
	SVC BusinessFunctionCodeEnum = "SVC"
	DRB BusinessFunctionCodeEnum = "DRB"
)