/*
 * Wire API
 *
 * Moov Wire implements an HTTP API for creating, parsing, and validating Fedwire messages.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// WireAmount Maximum amount is a penny less than $10 billion.
type WireAmount struct {
	// Amount is 12 numeric digits, right-justified with leading zeros. It has an implied decimal point and no commas (e.g., $12,345.67 becomes 000001234567). Can be all zeros for subtype 90.
	Amount string `json:"amount"`
}
