/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SenderSuppliedInfo {1500}
type SenderSuppliedInfo struct {
	// FormatVersion 30 
	FormatVersion string `json:"formatVersion"`
	// UserRequestCorrelation
	UserRequestCorrelation string `json:"userRequestCorrelation"`
	// TestProductionCode * `T` - Test * `P` - Production 
	TestProductionCode string `json:"testProductionCode"`
	// MessageDuplicationCode * ` ` - Original Message * `P` - Resend 
	MessageDuplicationCode string `json:"messageDuplicationCode"`
}
