/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// LocalInstrument is the local instrument
type LocalInstrument struct {
	LocalInstrumentCode LocalInstrumentEnum `json:"localInstrumentCode,omitempty"`
	// ProprietaryCode
	ProprietaryCode string `json:"proprietaryCode,omitempty"`
}
