/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DocumentTypeCodeEnum : DocumentTypeCode  * `AROI` - Accounts Receivable Open Item * `BOLD` - Bill of Lading Shipping Notice * `CINV` - Commercial Invoice * `CMCN` - Commercial Contract * `CNFA` - Credit Note Related to Financial Adjustment * `CREN` - Credit Note * `DEBN` - Debit Note * `DISP` - Dispatch Advice * `DNFA` - Debit Note Related to Financial Adjustment HIRI Hire Invoice * `MSIN` - Metered Service Invoice * `PROP` - Proprietary Document Type * `PUOR` - Purchase Order * `SBIN` - Self Billed Invoice * `SOAC` - Statement of Account * `TSUT` - Trade Services Utility Transaction VCHR Voucher 
type DocumentTypeCodeEnum string

// List of DocumentTypeCodeEnum
const (
	AROI DocumentTypeCodeEnum = "AROI"
	BOLD DocumentTypeCodeEnum = "BOLD"
	CINV DocumentTypeCodeEnum = "CINV"
	CMCN DocumentTypeCodeEnum = "CMCN"
	CNFA DocumentTypeCodeEnum = "CNFA"
	CREN DocumentTypeCodeEnum = "CREN"
	DEBN DocumentTypeCodeEnum = "DEBN"
	DISP DocumentTypeCodeEnum = "DISP"
	DNFA DocumentTypeCodeEnum = "DNFA"
	MSIN DocumentTypeCodeEnum = "MSIN"
	PROP DocumentTypeCodeEnum = "PROP"
	PUOR DocumentTypeCodeEnum = "PUOR"
	SBIN DocumentTypeCodeEnum = "SBIN"
	SOAC DocumentTypeCodeEnum = "SOAC"
	TSUT DocumentTypeCodeEnum = "TSUT"
)