/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SecondaryRemittanceDocumentInfoEnum : SecondaryRemittanceDocumentInfo  * `AROI` - Accounts Receivable Open Item * `DISP` - Dispatch Advice * `FXDR` - Foreign Exchange Deal Reference * `PROP` - Proprietary Document Type PUOR Purchase Order * `RADM` - Remittance Advice Message * `RPIN` - Related Payment Instruction * `SCOR1` - Structured Communication Reference VCHR Voucher 
type SecondaryRemittanceDocumentInfoEnum string

// List of SecondaryRemittanceDocumentInfoEnum
const (
	AROI SecondaryRemittanceDocumentInfoEnum = "AROI"
	DISP SecondaryRemittanceDocumentInfoEnum = "DISP"
	FXDR SecondaryRemittanceDocumentInfoEnum = "FXDR"
	PROP SecondaryRemittanceDocumentInfoEnum = "PROP"
	RADM SecondaryRemittanceDocumentInfoEnum = "RADM"
	RPIN SecondaryRemittanceDocumentInfoEnum = "RPIN"
	SCOR1 SecondaryRemittanceDocumentInfoEnum = "SCOR1"
)