/*
 * Wire API
 *
 * Moov Wire implements an HTTP API for creating, parsing, and validating Fedwire messages.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SenderReference struct for SenderReference
type SenderReference struct {
	// SenderReference
	SenderReference string `json:"senderReference,omitempty"`
}
