/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// FiPaymentMethodToBeneficiary struct for FiPaymentMethodToBeneficiary
type FiPaymentMethodToBeneficiary struct {
	// PaymentMethod
	PaymentMethod         string `json:"paymentMethod,omitempty"`
	AdditionalInformation string `json:"AdditionalInformation,omitempty"`
}
