/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TestProductionCodeEnum : TestProductionCode  * `T` - Test * `P` - Production 
type TestProductionCodeEnum string

// List of TestProductionCodeEnum
const (
	T TestProductionCodeEnum = "T"
	P TestProductionCodeEnum = "P"
)