/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SecondaryRemittanceDocumentEnum : SecondaryRemittanceDocument  * `AROI` - Accounts Receivable Open Item * `DISP` - Dispatch Advice * `FXDR` - Foreign Exchange Deal Reference * `PROP` - Proprietary Document Type PUOR Purchase Order * `RADM` - Remittance Advice Message * `RPIN` - Related Payment Instruction * `SCOR1` - Structured Communication Reference VCHR Voucher 
type SecondaryRemittanceDocumentEnum string

// List of SecondaryRemittanceDocumentEnum
const (
	AROI SecondaryRemittanceDocumentEnum = "AROI"
	DISP SecondaryRemittanceDocumentEnum = "DISP"
	FXDR SecondaryRemittanceDocumentEnum = "FXDR"
	PROP SecondaryRemittanceDocumentEnum = "PROP"
	RADM SecondaryRemittanceDocumentEnum = "RADM"
	RPIN SecondaryRemittanceDocumentEnum = "RPIN"
	SCOR1 SecondaryRemittanceDocumentEnum = "SCOR1"
)