/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// RelatedRemittance
type RelatedRemittance struct {
	// RemittanceIdentification
	RemittanceIdentification string `json:"remittanceIdentification,omitempty"`
	RemittanceLocationMethod RemittanceLocationMethodEnum `json:"remittanceLocationMethod,omitempty"`
	// RemittanceLocationElectronicAddress (E-mail or URL address)
	RemittanceLocationElectronicAddress string `json:"remittanceLocationElectronicAddress,omitempty"`
	RemittanceData RemittanceData `json:"remittanceData,omitempty"`
}
