/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AdjustmentInfoEnum : AdjustmentInfo  * `01` - Pricing Error * `03` - Extension Error * `04` - Item Not Accepted (Damaged) * `05` - Item Not Accepted (Quality) * `06` - Quantity Contested 07   Incorrect Product * `11` - Returns (Damaged) * `12` - Returns (Quality) * `59` - Item Not Received * `75` - Total Order Not Received * `81` - Credit as Agreed * `CM` - Covered by Credit Memo 
type AdjustmentInfoEnum string

// List of AdjustmentInfoEnum
const (
	_1 AdjustmentInfoEnum = "1"
	_3 AdjustmentInfoEnum = "3"
	_4 AdjustmentInfoEnum = "4"
	_5 AdjustmentInfoEnum = "5"
	_6 AdjustmentInfoEnum = "6"
	_11 AdjustmentInfoEnum = "11"
	_12 AdjustmentInfoEnum = "12"
	_59 AdjustmentInfoEnum = "59"
	_75 AdjustmentInfoEnum = "75"
	_81 AdjustmentInfoEnum = "81"
	CM AdjustmentInfoEnum = "CM"
)