/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MessageDuplicationCodeEnum : MessageDuplicationCode  * ` ` - Original Message * `R` - Retrieval of an original message * `P` - Resend 
type MessageDuplicationCodeEnum string

// List of MessageDuplicationCodeEnum
const (
	 MessageDuplicationCodeEnum = " "
	R MessageDuplicationCodeEnum = "R"
	P MessageDuplicationCodeEnum = "P"
)