/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// BeneficiaryReference struct for BeneficiaryReference
type BeneficiaryReference struct {
	// BeneficiaryReference
	BeneficiaryReference string `json:"beneficiaryReference,omitempty"`
}
