/*
 * Wire API
 *
 * Moov Wire implements an HTTP API for creating, parsing, and validating Fedwire messages.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// OutputMessageAccountabilityData struct for OutputMessageAccountabilityData
type OutputMessageAccountabilityData struct {
	// OutputCycleDate (Format CCYYMMDD - C=Century, Y=Year, M=Month, D=Day)
	OutputCycleDate string `json:"outputCycleDate,omitempty"`
	// OutputDestinationID
	OutputDestinationID string `json:"outputDestinationID,omitempty"`
	// OutputSequenceNumber
	OutputSequenceNumber string `json:"outputSequenceNumber,omitempty"`
	// Output Date is based on the calendar date. (Format MMDD - M=Month, D=Day)
	OutputDate string `json:"outputDate,omitempty"`
	// Output Time is based on a 24-hour clock, Eastern Time. (Format HHmm - H=Hour, m=Minute)
	OutputTime string `json:"outputTime,omitempty"`
	// OutputFRBApplicationIdentification
	OutputFRBApplicationIdentification string `json:"outputFRBApplicationIdentification,omitempty"`
}
