/*
 * Wire API
 *
 * Moov Wire implements an HTTP API for creating, parsing, and validating Fedwire messages.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// BeneficiaryReference struct for BeneficiaryReference
type BeneficiaryReference struct {
	// BeneficiaryReference
	BeneficiaryReference string `json:"beneficiaryReference,omitempty"`
}
