/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ErrorCategoryEnum :  * `E` - Data Error * `F` - Insufficient Balance * `H` - Accountability Error * `I` - In Process or Intercepted * `W` - Cutoff Hour Error * `X` - Duplicate IMAD 
type ErrorCategoryEnum string

// List of ErrorCategoryEnum
const (
	E ErrorCategoryEnum = "E"
	F ErrorCategoryEnum = "F"
	H ErrorCategoryEnum = "H"
	I ErrorCategoryEnum = "I"
	W ErrorCategoryEnum = "W"
	X ErrorCategoryEnum = "X"
)