/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PaymentNotificationIndicatorEnum : PaymentNotificationIndicator  * `0 - 6` - Reserved for market practice conventions. * `7 - 9` - Reserved for bilateral agreements between Fedwire senders and receivers. 
type PaymentNotificationIndicatorEnum string

// List of PaymentNotificationIndicatorEnum
const (
	_0 PaymentNotificationIndicatorEnum = "0"
	_1 PaymentNotificationIndicatorEnum = "1"
	_2 PaymentNotificationIndicatorEnum = "2"
	_3 PaymentNotificationIndicatorEnum = "3"
	_4 PaymentNotificationIndicatorEnum = "4"
	_5 PaymentNotificationIndicatorEnum = "5"
	_6 PaymentNotificationIndicatorEnum = "6"
	_7 PaymentNotificationIndicatorEnum = "7"
	_8 PaymentNotificationIndicatorEnum = "8"
	_9 PaymentNotificationIndicatorEnum = "9"
)