/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AccountDebitedDrawdown - AccountDebitedDrawdown is the account which is debited in a drawdown
type AccountDebitedDrawdown struct {

	// Identification Code * `D` - Debit 
	IdentificationCode string `json:"identificationCode"`

	// Identifier
	Identifier string `json:"identifier"`

	// Name
	Name string `json:"name"`

	// AddressLineOne
	AddressLineOne string `json:"addressLineOne,omitempty"`

	// AddressLineTwo
	AddressLineTwo string `json:"addressLineTwo,omitempty"`

	// AddressLineThree
	AddressLineThree string `json:"addressLineThree,omitempty"`
}
