/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateFile struct {

	// File ID
	Id string `json:"id,omitempty"`

	FedWireMessage []FedWireMessage `json:"fedWireMessage,omitempty"`
}
