/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// FiToFi - FIToFI
type FiToFi struct {

	// LineOne
	LineOne string `json:"lineOne,omitempty"`

	// LineTwo
	LineTwo string `json:"lineTwo,omitempty"`

	// LineThree
	LineThree string `json:"lineThree,omitempty"`

	// LineFour
	LineFour string `json:"lineFour,omitempty"`

	// LineFive
	LineFive string `json:"lineFive,omitempty"`

	// LineSix
	LineSix string `json:"lineSix,omitempty"`
}
