/*
 * WIRE API
 *
 * Moov WIRE () implements an HTTP API for creating, parsing and validating WIRE files.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		"GET",
		"/",
		Index,
	},

	{
		"CreateFile",
		strings.ToUpper("Post"),
		"/files/create",
		CreateFile,
	},

	{
		"DeleteFile",
		strings.ToUpper("Delete"),
		"/files/{file_id}",
		DeleteFile,
	},

	{
		"DeleteFileFEDWireMessage",
		strings.ToUpper("Delete"),
		"/files/{file_id}/fEDWireMessage/{fEDWireMessage_id}",
		DeleteFileFEDWireMessage,
	},

	{
		"GetFileByID",
		strings.ToUpper("Get"),
		"/files/{file_id}",
		GetFileByID,
	},

	{
		"GetFileContents",
		strings.ToUpper("Get"),
		"/files/{file_id}/contents",
		GetFileContents,
	},

	{
		"GetFileFEDWireMessage",
		strings.ToUpper("Get"),
		"/files/{file_id}/fEDWireMessage/{fEDWireMessage_id}",
		GetFileFEDWireMessage,
	},

	{
		"GetFiles",
		strings.ToUpper("Get"),
		"/files",
		GetFiles,
	},

	{
		"Ping",
		strings.ToUpper("Get"),
		"/ping",
		Ping,
	},

	{
		"UpdateFile",
		strings.ToUpper("Post"),
		"/files/{file_id}",
		UpdateFile,
	},

	{
		"ValidateFile",
		strings.ToUpper("Get"),
		"/files/{file_id}/validate",
		ValidateFile,
	},
}
