FROM golang:1.15-buster as builder
LABEL maintainer="Moov <support@moov.io>"
RUN apt-get update -qq && apt-get install -y git make
WORKDIR /go/src/github.com/moov-io/wire
COPY . .
WORKDIR /go/src/github.com/moov-io/wire/test/fuzz-reader
RUN make install
RUN make fuzz-build
ENTRYPOINT make fuzz-run
