FROM golang:1.14-buster as builder
RUN apt-get update -qq && apt-get install -y git make
WORKDIR /go/src/github.com/moov-io/wire
COPY . .
WORKDIR /go/src/github.com/moov-io/wire/test/fuzz-reader
RUN make install
RUN make fuzz-build
ENTRYPOINT make fuzz-run
